# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b3f17d8c-47a0-4161-8fad-46a7eadb9a0d";
      fsType = "ext4";
    };
  
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6766-C594";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4e83aecf-cc83-4dda-bec3-c3a451ce4cdb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
