# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "hid-tmff-new" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.hid-tmff2 ];

  hardware.firmware = [ pkgs.linux-firmware ];

  fileSystems = {

    "/" = { 
      device = "/dev/disk/by-uuid/e6343547-5be9-434d-ad4f-992690c00f75";
      fsType = "ext4";
    };
  
    "/boot" = {
      device = "/dev/disk/by-uuid/9C89-90E0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

    "/home" =
    { device = "/dev/disk/by-uuid/082b69a0-2b15-40c3-9049-0d637111e79d";
      fsType = "ext4";
    };
    
    "/home/HDD_EXT4" = {
      device = "UUID=b7cdd919-6246-4c33-84c3-b638e06a637c";
      fsType = "ext4";
      options = [ "rw" "nosuid" "nodev" "relatime" "errors=remount-ro" ];
      noCheck = false;
    };

    "/home/Games_SSD" = {
      device = "UUID=0d2b8ee3-93f5-4ee4-a3b7-6ef27fa2d1c3";
      fsType = "btrfs";
      options = [ "rw" "relatime" "ssd" "discard=async" "space_cache=v2" "subvol=/" ];
      noCheck = true;
    };

    "/home/Games_NVME" = {
      device = "UUID=eabe14ee-82de-4fb5-bf19-a785aa9c05c6";
      fsType = "btrfs";
      options = [ "rw" "relatime" "ssd" "discard=async" "space_cache=v2" "subvol=/" ];
      noCheck = true;
    };
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4e83aecf-cc83-4dda-bec3-c3a451ce4cdb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
